version: '3.8'

services:
  backend:
    build: ./backend_api
    ports:
      - "8000:8000"
    volumes:
      - ./core_ai_services:/app/core_ai_services
    environment:
      - PYTHONPATH=/app
    networks:
      - querycraft-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - querycraft-network

networks:
  querycraft-network:
    driver: bridge